addons:
  ssh_known_hosts: 188.226.165.39
language: php
script: phpunit test.php
before_deploy:
- openssl aes-256-cbc -K $encrypted_278b9bd33ccf_key -iv $encrypted_278b9bd33ccf_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after $TRAVIS_BUILD_DIR/dist travis@188.226.165.39:files/
  on:
    branch: develop